name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Delete previous image
        run: sudo docker rmi cafe-cicd || true
      - name: Pull Docker image
        run: sudo docker pull fabrice7891/cafe-system:latest
      - name: Delete Old docker container
        run: sudo docker rm -f cafe-system-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8081:8081 --name cafe-system-container fabrice7891/cafe-system