name: CI - Build, Scan, Push and Trigger CD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [dev, 'rc-*']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      ECR_REPO: ${{ secrets.ECR_REPO }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      REPO_DEPLOY: ${{ secrets.REPO_DEPLOY }}
      ENV: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'dev' && 'dev' || 'feature' }}
      ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
      REPO_NAME: ${{ secrets.REPO_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActionsECRRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Set environment tag
#        id: tag
#        run: |
#          SHA=$(echo ${{ github.sha }} | cut -c1-8)
#          BRANCH="${{ github.ref }}"
#          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
#            BASE="${{ github.base_ref }}"
#            if [[ "$BASE" == "dev" ]]; then
#              TAG="feature-${SHA}"
#            elif [[ "$BASE" == rc-* ]]; then
#              TAG="staging-${SHA}"
#            else
#              TAG="pr-${SHA}"
#            fi
#          elif [[ "$BRANCH" == "refs/heads/main" ]]; then
#            TAG="prod-${SHA}"
#          elif [[ "$BRANCH" == "refs/heads/dev" ]]; then
#            TAG="dev-${SHA}"
#          else
#            TAG="unknown-${SHA}"
#          fi
#          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Set environment tag with date
        id: tag
        run: |
          SHA=$(echo ${{ github.sha }} | cut -c1-8)
          DATE=$(date +%Y%m%d)              
          BRANCH="${{ github.ref }}"
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            BASE="${{ github.base_ref }}"
            if [[ "$BASE" == "dev" ]]; then
              TAG="feature-${SHA}-${DATE}"  
            elif [[ "$BASE" == rc-* ]]; then
              TAG="staging-${SHA}-${DATE}"  
            else
              TAG="pr-${SHA}-${DATE}"       
            fi
          elif [[ "$BRANCH" == "refs/heads/main" ]]; then
            TAG="prod-${SHA}-${DATE}"      
          elif [[ "$BRANCH" == "refs/heads/dev" ]]; then
            TAG="dev-${SHA}-${DATE}"        
          else
            TAG="unknown-${SHA}-${DATE}"    
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and Test
        run: mvn clean install -DskipTests=false

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true

      - name: Test docker login
        run: docker info

      - name: Debug ECR_REPO and Tag  (Optional)
        run: |
          echo "ECR_REPO='${{ github.ref_name }}'"
          echo "TAG='${{ steps.tag.outputs.tag }}'"
          echo "Full image name: $ECR_REGISTRY/${{ env.REPO_NAME }}:${{ steps.tag.outputs.tag }}"
          echo "ECR_REPO='${{ env.ECR_REPO }}'"
          

      - name: Build Docker image
        run: |
          docker build -t $ECR_REGISTRY/${{ env.REPO_NAME }}:${{ steps.tag.outputs.tag }} .
          
      - name: List local Docker images
        run: docker images
          

      - name: Push Docker image
        run: |
          docker push $ECR_REGISTRY/${{ env.REPO_NAME }}:${{ steps.tag.outputs.tag }}

      # Optionnel : déclencher workflow CD
      - name: Trigger CD
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ env.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ env.REPO_DEPLOY }}
          event-type: deploy
          client-payload: >-
            {
              "branch": "${{ github.ref_name }}",
              "image_tag": "${{ steps.tag.outputs.tag }}",
              "environment": "${{ env.ENV }}",
              "microservice": "microservice-a"
            }
